# Generated by Django 4.2.3 on 2023-07-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_repositoryapikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositoryapikey',
            name='key',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
