# Generated by Django 4.2.3 on 2023-07-10 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_alter_repositoryapikey_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pre_release', models.BooleanField(default=False)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='apps.repository')),
            ],
        ),
        migrations.CreateModel(
            name='RepositoryArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_key', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='apps.repositoryrelease')),
            ],
        ),
    ]
