# Generated by Django 4.2.3 on 2023-07-10 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_repositoryrelease_repositoryartifact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RepositoryArtifact',
            new_name='RepositoryReleaseArtifact',
        ),
    ]
