# Generated by Django 4.2.3 on 2023-07-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_rename_repositoryartifact_repositoryreleaseartifact'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositoryreleaseartifact',
            name='size',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
