# Generated by Django 4.2.3 on 2023-07-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_repositoryapikey_user_repositoryrelease_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
